### ISSUE TITLE
Benchmark client 可以提供一下吗

### ISSUE THREAD

**Issue by SpikeWong** [lxzan/go-websocket-testing#1]

**Comment by lxzan** [comment]
tcpkali , 可能需要自己编译
https://github.com/satori-com/tcpkali

**Comment by lxzan** [comment]
这个项目里面的gws需要更新到最新版本

**Comment by SpikeWong** [comment]
我没怎么配置过 grafana dashboard, 请教下 assets 目录下的那些 grafana 模板该怎么搭呢

**Comment by lxzan** [comment]
先安装配置Prometheus, 然后在从 assets/config/grafana-dashboard.json 复制配置并导入到Grafana

**Comment by SpikeWong** [comment]
压完了，我用 https://github.com/plantain-00/ws-benchmark 压的。其中一个场景是瞬时并发 3500，总共请求 35000 次，payload 是一个 3kb 大小的文本，这个场景下 lxzan 的稳定性（成功请求数/总请求数）确实比别的框架好


框架 | 稳定性 | P99 延迟(ms) | MAX 内存(MB)
-- | -- | -- | --
https://github.com/gobwas/ws | 2.2% | N/A | N/A
https://github.com/gorilla/websocket | 85% | 0.208.5 | 32.5
https://github.com/lxzan/gws | 100% | 0.234.5 | 69
https://github.com/nhooyr/websocket | 11.6% | N/A | N/A

</div><div class="mp-table-serialize-flag"><br/></div></div><span data-morpho-doc-data='{"token":"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiYXBwSWQiOjEsInVpZCI6IkRabE5kRWxpMVUiLCJkb2NJZCI6InB2OUpxeDRpTldWU2ZMIn0..fi7nIlPA_flaTgcd.D-HaLDxzNo99HFry79X7-A-aSDyFZ4Wq_G7tAgSQ7D33brZXXJgt0FcfTsoaZA8wAQeF6gNg3DTlotTBqo9MaBtkP1HTw8lkR4CdEidzcjxi3FhAymj4Ve886lotX_jpTyZ0fPMnj_EVKH2db8IwZB2HET5LFglWYewo5WG2cF2IU1HrLWl41Mb9mY98MbFA44e6-3kxx-KeSRs1d6D4QH511A.rzWdeEBQtsOXk4rVtcesOQ"}' class='mp-morpho-clipboard-doc-data'></span>

**Comment by lxzan** [comment]
升级gws到最新版本, 使用NewServer启动服务, 内存占用可以降低一大截

**Comment by lxzan** [comment]
用go写一个wsbench, iops还会高很多

<img width="806" alt="image" src="https://user-images.githubusercontent.com/17956540/234847189-caa865ea-ecc9-4e31-8996-4c6d139a6dff.png">

**Comment by lxzan** [comment]
没想到gorilla也有一些请求失败，它的实现比其他两个要好些

**Comment by SpikeWong** [comment]
我想问下在 handler 里面单独起一个 goroutine 来处理 websocket 写入和读取事件好，还是直接在原来的 handler 里面一个 for 循环就 ok 呢? 两者在性能上和稳定性上会差距很大吗？

**Comment by lxzan** [comment]
> 我想问下在 handler 里面单独起一个 goroutine 来处理 websocket 写入和读取事件好，还是直接在原来的 handler 里面一个 for 循环就 ok 呢? 两者在性能上和稳定性上会差距很大吗？

性能差不多. 开启新的goroutine是为了让请求上下文顺利被gc, 内存方面稍微好点.

**Comment by lxzan** [comment]
实际上有些东西就是gc不了, 所以我后面自己实现了http parser, 内存占用降低了一大截

https://github.com/golang/go/issues/59567

**Comment by SpikeWong** [comment]
佩服，感觉你对这块的理解很深呀。

**Comment by lxzan** [comment]
在开发gws的过程中学到了很多东西

**Comment by SpikeWong** [comment]
是什么样的契机想让你开发这个的？

**Comment by lxzan** [comment]
> 是什么样的契机想让你开发这个的？

因为我觉得流行的这些golang websocket package api设计得不好, 不如js websocket event简单明了. 后面发现它们性能也不够好.

**Comment by lxzan** [comment]
ubuntu跑了下35万个请求

![image](https://user-images.githubusercontent.com/17956540/235157303-caeffbc7-b705-449c-87e3-5ccf27ab1053.png)

**Comment by lxzan** [comment]
可以试试我写的这个压测工具, https://github.com/lxzan/wsbench

**Comment by SpikeWong** [comment]
哥真的挺高产的，啥公司有这么多的自己的时间？

**Comment by lxzan** [comment]
> 哥真的挺高产的，啥公司有这么多的自己的时间？

😂
